Algoritmo "estruraEnquanto"

Var

    x, y : inteiro

Inicio

      Escreval ("Digite dois números: ")
      Leia (x)
      Leia (y)
      
 Enquanto x <> y faca
 
  Se x > y entao
     Escreval ("DECRESCENTE!")
  senao
       se x < y entao
          Escreval ("CRESCENTE!")
       fimse
  fimse

  Escreval ("Digite outros dois números: ")
  Leia (x)
  Leia (y)
  
 FimEnquanto
  


Fimalgoritmo