Algoritmo "senha_fixa"

Var

   senha, senhaFixa : real
   login, loginFixo : caractere

Inicio


      Escreval("Crie um usuário e/ou e-mail: ")
      Leia(loginFixo)
      
      Escreval("Crie uma senha: ")
      Leia(senhaFixa)
      
      escreval()
      
      Escreval("-------------------------------------------------")
      
      escreval()
      
      Escreval("Digite seu login: ")
      Leia(login)
      
      Escreval("Digite sua senha: ")
      Leia(senha)
      
         enquanto (login <> loginFixo) ou (senha <> senhaFixa) faca
         
           escreval()
           
           escreval("Login e/ou senha Inválido! Tente novamente...")
           
           escreval()
           
           escreval("--------------------------------------------")
           
           escreval()
           
           escreval("Digite seu login: ")
           leia(login)
           escreval("Digite sua senha: ")
           leia(senha)
           
         fimenquanto

      escreval()
      
      Escreval("Acesso permitido!")
      

      

      

Fimalgoritmo